version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./volume/conf:/mosquitto/config"
      - "./volume/data:/mosquitto/data"
      - "./volume/log:/mosquitto/log"
